name: Build
on:
  pull_request:
    branches: [dev, main]
jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: install
        uses: ./.github/actions/install

      - name: Build frontend
        uses: ./.github/actions/build
